import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-poppins", // Define a CSS variable for easier use
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Include desired weights
});

export const metadata: Metadata = {
	title: "Street Xchange",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${poppins.variable} antialiased`}>
				{children}
			</body>
		</html>
	);
}
